ERROR 2025-07-18 12:55:06,327 log 22852 5556 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\generators.py", line 252, in parse
    operation = view.schema.get_operation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 99, in get_operation
    request_body = self._get_request_body()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1295, in _get_request_body
    schema, partial_request_body_required = self._get_request_for_media_type(serializer, direction)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1327, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `organization_name` is not valid for model `User`.
ERROR 2025-07-18 12:55:06,576 log 22852 5556 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\generators.py", line 252, in parse
    operation = view.schema.get_operation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 99, in get_operation
    request_body = self._get_request_body()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1295, in _get_request_body
    schema, partial_request_body_required = self._get_request_for_media_type(serializer, direction)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1327, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `organization_name` is not valid for model `User`.
ERROR 2025-07-18 12:55:17,147 log 22852 23648 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\generators.py", line 252, in parse
    operation = view.schema.get_operation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 99, in get_operation
    request_body = self._get_request_body()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1295, in _get_request_body
    schema, partial_request_body_required = self._get_request_for_media_type(serializer, direction)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1327, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\drf_spectacular\openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jasmina\PycharmProjects\CerifyNow-API-org\.venv\Lib\site-packages\rest_framework\serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `organization_name` is not valid for model `User`.
